# Generated by Django 2.0.1 on 2018-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='dateUploaded',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='title',
        ),
    ]
