# Generated by Django 2.0.1 on 2018-02-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datavisual', '0002_auto_20180206_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datavisual.Document'),
        ),
    ]
