# Generated by Django 2.0.1 on 2018-02-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datavisual', '0003_callrecord_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelParser',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datavisual.Document')),
            ],
            bases=('datavisual.document',),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
    ]
