# Generated by Django 2.0.1 on 2018-02-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavisual', '0004_auto_20180207_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelparser',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='document',
        ),
        migrations.DeleteModel(
            name='ExcelParser',
        ),
    ]
